kind: pipeline
type: exec
name: backend

steps:
  - name: 'git pull'
    commands:
      - cd /var/www/projects/github-battle
      - git pull
  - name: 'docker compose'
    commands:
      - cd /var/www/projects/github-battle
      - docker-compose up -d --build
