version: '3.8'

services:
  github-battle:
    container_name: github-battle
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

networks:
  default:
    external:
      name: external-network
